export const ERROR_CODES = {
  VALIDATION: "VALIDATION_ERROR",
  INTERNAL: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UPLOAD_ERROR: "UPLOAD_ERROR",

  COMPLAINT_NOT_FOUND: "COMPLAINT_NOT_FOUND",
  COMPLAINT_VALIDATION: "COMPLAINT_VALIDATION_ERROR",
};
