export const ERROR_CODES = {
  VALIDATION: "VALIDATION_ERROR",
  INTERNAL: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UPLOAD_ERROR: "UPLOAD_ERROR",

  COMPLAINT_NOT_FOUND: "COMPLAINT_NOT_FOUND",
  COMPLAINT_VALIDATION: "COMPLAINT_VALIDATION_ERROR",

  EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  INVALID_EMAIL: "INVALID_EMAIL",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
};
