export const ERROR_CODES = {
  VALIDATION: "VALIDATION_ERROR",
  INTERNAL: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  UPLOAD_ERROR: "UPLOAD_ERROR",
  PAGINATION_VALIDATION: "PAGINATION_VALIDATION_ERROR",
  ROUTE_SERVICE_UNAVAILABLE: "ROUTE_SERVICE_UNAVAILABLE",

  COMPLAINT_NOT_FOUND: "COMPLAINT_NOT_FOUND",
  COMPLAINT_VALIDATION: "COMPLAINT_VALIDATION_ERROR",
  COMPLAINT_INVALID_STATUS_TRANSITION: "COMPLAINT_INVALID_STATUS_TRANSITION",
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  COMMENT_VALIDATION: "COMMENT_VALIDATION_ERROR",
  COMMENT_ALREADY_LIKED: "COMMENT_ALREADY_LIKED",

  EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  INVALID_EMAIL: "INVALID_EMAIL",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
};
